config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'welcome/index'

  resources :keys

  resources :gates do
	  resources :keys
  end

  root 'welcome#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gate.rb
class Gate < ApplicationRecord
	has_many :keys
end

app/models/key.rb
class Key < ApplicationRecord
	belongs_to :gates
	 validates :codigo, presence: true,
                    length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gates_controller.rb
class GatesController < ApplicationController
  def new 
  	@gate = Gate.new
  	#@key = @gate.keys.create
  end

  def create
    @gate = Gate.find(params[:gate_id])
    @key = @gate.keys.create(key_params)
    redirect_to gate_path(@gate)
  end
 
  private
    def key_params
      params.require(:key).permit(:codigo, :numero_de_copia)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
	def index
        @key = Key.all
 	end

	def show
	    @key = Key.find(params[:id])
	end

	def new
		@key = Key.new
	end

	def edit
  		@key = Key.find(params[:id])
	end

	def create
		@key = Key.new(params.required(:key).permit(:codigo, :numero_de_copia))

		if @key.save	
	        redirect_to keys_path

	       else
	       	render 'new'
	       end
    end

    def update
  	    @key = Key.find(params[:id])
 
		if @key.update(key_params)
		    redirect_to keys_path
		else
		    render 'edit'
		end
	end

	def destroy
 		@key = Key.find(params[:id])
  		@key.destroy

   		redirect_to keys_path
	end

    private
    	def key_params
		  params.required(:key).permit(:codigo, :numero_de_copia)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gates/_form.html.erb
 <%= form_for(@gate) do |f| %>

     
      <% if @gate.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@gate.errors.count, "error") %> esta llave no puede ser guardada:
          </h2>
          <ul>
            <% @gate.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
     
      <div class="form-group">
        <%=f.label :codigo %>
        <%=f.text_field :codigo, :class => "form-control", placeholder: 'Ej. 44'%>
      </div>
     
     
     <div class="form-group">
        <%=f.label :ubicacion %>
        <%=f.text_field :ubicacion, :class => "form-control", placeholder: 'Locación'%>
      </div>

     <div class="form-group">
        <%=f.label :descripcion %>
        <%=f.text_field :descripcion, :class => "form-control", placeholder: 'Observaciones'%>
      </div>
     
     <h3>Área</h3>

     <div class="checkbox">
     
          <label>
            <%= check_box_tag "laboratorio", "yes" %>
            Laboratorio
          </label>


            <label>
                <%= check_box_tag "Oficina", "yes" %>
                Oficina
            </label>


            <label>
                <%= check_box_tag "aula", "yes" %>
                Aula
            </label>


            <label>
                <%= check_box_tag "otro", "yes" %>
                Otro
            </label>
      </div>

      <h2>Agregar llave:</h2>
      
      <div class="form-group"> 
        <%= link_to 'Volver', gates_path, class: 'btn btn-default' %>
          <%=f.submit 'Guardar', :class=> "btn btn-success"%>
      </div>


      
    <% end %>

app/views/gates/new.html.erb
<h1>Nueva Puerta</h1>

<%= render 'form' %>

app/views/gates/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @gate.codigo %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @gate.ubicacion %>
</p>
 
<h2>Add a key:</h2>
<%= form_with(model: [ @gate, @gate.keys.build ], local: true) do |form| %>
  <p>
    <%= form.label :keyer %><br>
    <%= form.text_field :keyer %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_gate_path(@gate) %> |
<%= link_to 'Back', gates_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/keys/_form.html.erb
 <%= form_for(@key) do |f| %>

     
      <% if @key.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@key.errors.count, "error") %> esta llave no puede ser guardada:
          </h2>
          <ul>
            <% @key.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
     
      <div class="form-group">
        <%=f.label :codigo %>
        <%=f.text_field :codigo, :class => "form-control", placeholder: "Ej. 44" %>
      </div>
     
     
     <div class="form-group">
        <%=f.label :numero_de_copia %>
        <%=f.text_field :numero_de_copia, :class => "form-control", placeholder: "En número"%>
      </div>
     
     
      <div class="form-group"> 
        <%= link_to 'Volver', keys_path, class: 'btn btn-default' %>
          <%=f.submit 'Guardar', :class=> "btn btn-success"%>
      </div>


      
    <% end %>

app/views/keys/edit.html.erb
    <h1>Editar Llave</h1>

    <%= render 'form' %>
     
   


 

app/views/keys/index.html.erb
<h1>Lista de Llaves</h1>
 
<%= link_to 'Llave Nueva', new_key_path %>

  <table class="table table-striped">

    <tr>
      <th>Codigo</th>
      <th>Numero de copia</th>
      <th>  </th>
      <th colspan="3"></th>
    </tr>
   
    <% @key.each do |key| %>
      <tr>
        <td><%= key.codigo %></td>
        <td><%= key.numero_de_copia %></td>
        <td><%= link_to 'Editar', edit_key_path(key) %></td>
        <td><%= link_to 'Eliminar', key_path(key),
              method: :delete,
              data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </table>

app/views/keys/new.html.erb
<h1>Nueva Llave</h1>

<%= render 'form' %>

app/views/keys/show.html.erb
<p>
  <strong>Codigo:</strong>
  <%= @key.codigo %>
</p>
 
<p>
  <strong>Numero_de_copia:</strong>
  <%= @key.numero_de_copia %>
</p>


<p>
  <strong>Codigo:</strong>
  <%= @key.codigo %>
</p>
 
<p>
  <strong>Nuemro_de_copia:</strong>
  <%= @key.numero_de_copia %>
</p>
 
<%= link_to 'Editar', edit_key_path(@key) %> |
<%= link_to 'Volver', key_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Door</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Llaves</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active">
		        <%= link_to 'Lista de Llaves', keys_path %>
	        </li>
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Puerta</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<%= yield %>
	</div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hi!</h1>
<%= link_to 'My Door', controller: 'keys' %>